services:
  db:
    image: postgres:16
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        pip install -r requirements.txt
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - db

  firebase:
    build:
      context: .
      dockerfile: firebase.Dockerfile
    working_dir: /firebase
    ports:
      - "9099:9099"   # Auth
      - "8080:8080"   # Firestore
      - "9000:9000"   # Realtime Database
      - "4000:4000"   # UI Emulator
      - "4400:4400"   # Emulator Hub
    volumes:
      - firebase_data:/firebase_data

volumes:
  postgres_data:
  firebase_data:
